import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import { ANN, FILE, BROWSER } from './lib.mjs';
const b = await chromium.launch({ executablePath: BROWSER });
const p = await (await b.newContext({ viewport:{width:1680,height:1050}, deviceScaleFactor:2 })).newPage();
const errs=[]; p.on('pageerror',e=>errs.push('P: '+e.message)); p.on('console',m=>{if(m.type()==='error')errs.push('C: '+m.text());});
await p.addInitScript(ANN);
await p.goto(FILE,{waitUntil:'load'});
await p.evaluate(()=>sessionStorage.setItem('qa-session',JSON.stringify({name:'Arlind Sylaj',role:'admin',ts:Date.now()})));
await p.reload({waitUntil:'load'}); await p.waitForTimeout(2200);
await (await p.$('label:has-text("Import Story+Bug CSV") input[type=file]')).setInputFiles('data/backlog_assignee.csv');
await p.waitForTimeout(2200);
const sel = await p.evaluate(()=>{const s=[...document.querySelectorAll('select')].find(x=>[...x.options].some(o=>/All assignees/.test(o.text))); return s?[...s.options].map(o=>o.text):null;});
console.log('1. dropdown:', sel);
const hdr = await p.evaluate(()=>[...document.querySelectorAll('div')].filter(d=>(d.textContent||'').trim()==='Assignee'&&d.getBoundingClientRect().width>0).length);
console.log('2. Assignee header present:', hdr>0);
const before = await p.evaluate(()=>(document.body.innerText.match(/GCSAP-5\d\d\d/g)||[]).length);
console.log('3. rows before filter:', before);
await p.evaluate(()=>{const s=[...document.querySelectorAll('select')].find(x=>[...x.options].some(o=>/All assignees/.test(o.text)));
  s.value='L. Haas'; s.dispatchEvent(new Event('change',{bubbles:true}));});
await p.waitForTimeout(1200);
const after = await p.evaluate(()=>(document.body.innerText.match(/GCSAP-5\d\d\d/g)||[]));
console.log('4. after filtering to L. Haas:', after.join(' '), '(expect 2)');
await p.evaluate(()=>{const s=[...document.querySelectorAll('select')].find(x=>[...x.options].some(o=>/All assignees/.test(o.text)));
  s.value='Unassigned'; s.dispatchEvent(new Event('change',{bubbles:true}));});
await p.waitForTimeout(1200);
console.log('5. Unassigned:', (await p.evaluate(()=>(document.body.innerText.match(/GCSAP-5\d\d\d/g)||[]))).join(' '), '(expect 2)');
await p.evaluate(()=>{const s=[...document.querySelectorAll('select')].find(x=>[...x.options].some(o=>/All assignees/.test(o.text)));
  s.value='All assignees'; s.dispatchEvent(new Event('change',{bubbles:true}));});
await p.waitForTimeout(900);
await p.evaluate(()=>{const h=[...document.querySelectorAll('div')].find(x=>/^Release Backlog × Testing Link/.test((x.textContent||'').trim()));
  if(h) window.scrollTo(0, h.getBoundingClientRect().top+window.scrollY-50);});
await p.waitForTimeout(800);
const hb = await p.evaluate(()=>{const h=[...document.querySelectorAll('div')].find(x=>/^Release Backlog × Testing Link/.test((x.textContent||'').trim())); const b=h.getBoundingClientRect(); return {x:b.x,y:b.y};});
await p.screenshot({path:'shots/p-asg.png', clip:{x:Math.max(0,hb.x-28), y:Math.max(0,hb.y-28), width:Math.min(1680-Math.max(0,hb.x-28),1200), height:600}});
console.log('errors:', errs.length?errs:'none');
await b.close();
