import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import { ANN, FILE, BROWSER } from './lib.mjs';
const b = await chromium.launch({ executablePath: BROWSER });
const p = await (await b.newContext({ viewport:{width:1680,height:1050}, deviceScaleFactor:2 })).newPage();
const errs=[]; p.on('pageerror',e=>errs.push('P: '+e.message)); p.on('console',m=>{if(m.type()==='error')errs.push('C: '+m.text());});
await p.addInitScript(ANN);
await p.goto(FILE,{waitUntil:'load'});
await p.evaluate(()=>sessionStorage.setItem('qa-session',JSON.stringify({name:'Arlind Sylaj',role:'admin',ts:Date.now()})));
await p.reload({waitUntil:'load'}); await p.waitForTimeout(2200);
await (await p.$('label:has-text("Import XLS / CSV") input[type=file]')).setInputFiles('data/qtest_uneven.csv');
await p.waitForTimeout(6000);
const shot = async (name) => {
  await p.evaluate(()=>{const h=[...document.querySelectorAll('div')].find(x=>/^Test environments$/.test((x.textContent||'').trim()));
    if(h) window.scrollTo(0,h.getBoundingClientRect().top+window.scrollY-30);});
  await p.waitForTimeout(900);
  const hb = await p.evaluate(()=>{const h=[...document.querySelectorAll('div')].find(x=>/^Test environments$/.test((x.textContent||'').trim())); const b=h.getBoundingClientRect(); return {x:b.x,y:b.y};});
  await p.screenshot({path:`shots/${name}.png`, clip:{x:Math.max(0,hb.x-28),y:Math.max(0,hb.y-28),width:Math.min(1680-Math.max(0,hb.x-28),1210),height:520}});
  console.log('  ✓', name);
};
console.log('view:', await p.evaluate(()=>localStorage.getItem('qa-envview')||'cards'));
await shot('env-cards');
await p.evaluate(()=>{const b=[...document.querySelectorAll('button')].find(e=>/Cards|Compact/.test((e.textContent||'').trim())); b&&b.click();});
await p.waitForTimeout(1400);
console.log('after toggle:', await p.evaluate(()=>localStorage.getItem('qa-envview')));
await shot('env-compact');
console.log('errors:', errs.length?errs:'none');
await b.close();
