import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import { ANN, FILE, BROWSER } from './lib.mjs';
const b = await chromium.launch({ executablePath: BROWSER });
const p = await (await b.newContext({ viewport:{width:1680,height:1050}, deviceScaleFactor:2 })).newPage();
const errs=[]; p.on('pageerror',e=>errs.push('P: '+e.message)); p.on('console',m=>{if(m.type()==='error')errs.push('C: '+m.text());});
await p.addInitScript(ANN);
await p.goto(FILE,{waitUntil:'load'});
await p.evaluate(()=>sessionStorage.setItem('qa-session',JSON.stringify({name:'Arlind Sylaj',role:'admin',ts:Date.now()})));
await p.reload({waitUntil:'load'}); await p.waitForTimeout(2200);
await (await p.$('label:has-text("Import Jira CSV") input[type=file]')).setInputFiles('data/jira_recurring.csv');
await p.waitForTimeout(2500);
const t = await p.evaluate(()=>document.body.innerText);
const sec = (t.match(/Recurring Defects across Environments[\s\S]{0,1400}/)||[''])[0];
console.log(sec.replace(/\n{2,}/g,'\n').split('\n').filter(Boolean).slice(0,40).join('\n'));
console.log('\nerrors:', errs.length?errs:'none');
await p.evaluate(()=>{const h=[...document.querySelectorAll('div')].find(x=>/^Recurring Defects across Environments/.test((x.textContent||'').trim()));
  if(h) window.scrollTo(0,h.getBoundingClientRect().top+window.scrollY-40);});
await p.waitForTimeout(800);
const hb = await p.evaluate(()=>{const h=[...document.querySelectorAll('div')].find(x=>/^Recurring Defects across Environments/.test((x.textContent||'').trim())); const b=h.getBoundingClientRect(); return {x:b.x,y:b.y};});
await p.screenshot({path:'shots/p-xenv.png', clip:{x:Math.max(0,hb.x-30),y:Math.max(0,hb.y-30),width:Math.min(1680-Math.max(0,hb.x-30),1200),height:780}});
await b.close();
